name: CI - Distzilla

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  perl-job:
    runs-on: [self-hosted, "${{ matrix.architecture }}", "kernel-${{kernel-version}}" ]
    container:
      image: perl:${{ matrix.perl-version }}
    strategy:
      fail-fast: false
      matrix:
        kernel-version:
          - "5.10"
          - "5.6"
        architecture:
          - X64
        perl-version:
          - '5.32'
          - 'latest'
    name: Perl ${{ matrix.perl-version }}:${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          cpanm --verbose --notest Perl::PrereqScanner Perl::Critic Perl::Critic::Freenode Dist::Zilla
          dzil authordeps --missing | cpanm --verbose
          dzil listdeps --missing --develop --author | cpanm --verbose
      - name: Regular tests
        run: |
          dzil test
      - name: X Tests
        run: |
          dzil xtest
